### PR TITLE
make test pass, add setlocale

### PR DESCRIPTION
**Pull request by mishin**
Hi  Gabot, I add use POSIX qw(setlocale LC_CTYPE);
to pass test
in non-US environment

### CODE REVIEW

**Comment by mishin** [comment]
Gabor, It's very strange behavior, I simple add `use Modern::Perl;` to `t/american.t` and `prove -Ilib t
` pass OK

**Comment by szabgab** [comment]
Modern::Perl just loads a bunch of other modules. Could you please find out which one of those is actually needed and update the change to use only that?

**Comment by mishin** [comment]
yes, It's a challenge, I'll found it!

**Comment by mishin** [comment]
Szabo, http://forum.pragmaticperl.com/threads/24-perl-%D0%BC%D0%B0%D0%B3%D0%B8%D1%8F?t=1432069177#reply-286 helps me, it's use feature unicode_strings;

**Comment by szabgab** [comment]
I was hoping to get an updated pull-request with the test passing. Would you have time to do that?

**Comment by mishin** [comment]
Well, Gabor, give me a week. Thanks. I have a bit time.

**Comment by manwar** [comment]
Hi @mishin 

Have you had chance to look into the failed test?
I recently adopted this module and going through all pending PRs.

Many Thanks.
Best Regards,
Mohammad S Anwar

**Comment by mishin** [comment]
Thanks @manwar. I'll look them up

**Comment by manwar** [comment]
Hi @mishin 

Any luck with the above request?

Best Regards,
Mohammad S Anwar

**Comment by manwar** [comment]
Thanks @mishin

**Pull request merged**
